version: '3.7'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=your_db
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
    ports:
      - "5431:5432"    
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "85:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=your_email_admin
      - PGADMIN_DEFAULT_PASSWORD=your_password_admin
    restart: unless-stopped